apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: org-runners-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: org-runners

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      scaleUpThreshold: "5"
      scaleDownThreshold: "1"
      scaleUpFactor: "2"
      scaleDownFactor: "0.5"