name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: kubernetes

    steps:
      - name: Test
        run: |
          echo "Runner funcionando"
          hostname
          whoami